= Asciidoctor::WildFly Docker
Maxime Gréau <https://github.com/mgreau[@mgreau]>
:page-layout: base
:idprefix:
ifdef::env-github[:idprefix: user-content-]
:idseparator: -
:source-language: java
:language: {source-language}
:uri-asciidoctor: {uri-docs}/what-is-asciidoctor
:uri-repo: https://github.com/mgreau/docker-asciidoctorj
:uri-issues: {uri-repo}/issues
:uri-discuss: http://discuss.asciidoctor.org
:uri-arquillian-cube-project: https://github.com/arquillian/arquillian-cube

The *Docker AsciidoctorJ* project ensure that AsciidoctorJ can be used by into a Java EE Application Server (WildFly AS for now).
This repository provides :

* a Dockerfile to build an image included WildFly 8.2 / AsciidoctorJ 1.5.2 / AsciidoctorJ-PDF 1.5.0
* Arquillian tests that used a docker container to convert AsciiDoc files to HTML and PDF files 

+
WARNING: asciidoctorj-epub3 is not working yet in this configuration.


== All in one with Arquillian : Build the Docker image and execute tests in a container

. Clone this project :

 $ git clone {uri-repo}.git

. Ensure Java, Maven and Docker are installed
. Execute tests (Build a docker image / Start a container / Execute tests / Stop and destroy the container)

  mvn clean test -Pwildfly82_dockerfile


== Build the docker image with Docker and THEN execute tests with Arquillian

. How to build the Docker image with docker command :
.. Clone this project :

 $ git clone {uri-repo}.git

.. Build the Docker image

  cd docker-asciidoctorj
  docker build -t asciidoctor/asciidoctorj-wildfly82 dockerfiles/wildfly82/

. How to execute the Arquillian Tests using an existing Docker image
.. Ensure Java, Maven and Docker are installed, and that the Docker image *asciidoctor/asciidoctorj-wildfly* is present in your registry.

  docker images
  
.. Execute tests (Start a container / Execute tests / Stop and destroy the container)

  mvn clean test -Pwildfly82
  
[IMPORTANT]
====
 Until the Docker image is present in your registry, you can just execute the Maven command (2b) !
====
  
[NOTE]
====
You can pass the docker server ip/port configuration with Maven properties :

  mvn clean test -Pwildfly82 -Ddocker.serverIp=192.168.59.103 -Ddocker.serverPort=2376
====

== Errors

=== Error with asciidoctorj-epub3

The asciidoctorj-epub3 doesn't work for now, there is an error :

----
"(LoadError) load error: nokogiri/nokogiri -- java.lang.NoClassDefFoundError: com/sun/org/apache/xpath/internal/VariableStackHTML
----
