= Asciidoctor::WildFly Docker
Maxime Gréau <https://github.com/mgreau[@mgreau]>
:page-layout: base
:idprefix:
ifdef::env-github[:idprefix: user-content-]
:idseparator: -
:source-language: java
:language: {source-language}
:uri-asciidoctor: {uri-docs}/what-is-asciidoctor
:uri-repo: https://github.com/mgreau/asciidoctor-wildlfy-docker
:uri-issues: {uri-repo}/issues
:uri-discuss: http://discuss.asciidoctor.org
:uri-arquillian-cube-project: https://github.com/arquillian/arquillian-cube

Asciidoctor WildFly Docker ensure that Asciidoctor projects work into a Java EE Application Server.
This repository provides :

* a Dockerfile image included WildFly 8.2 / AsciidoctorJ 1.5.2 / AsciidoctorJ-PDF 1.5.0
* Arquillian tests that used this docker image to convert AsciiDoc files to HTML and PDF files 

+
WARNING: asciidoctorj-epub3 is not working yet in this configuration.

== How to execute the Arquillian Tests

. Ensure Java, Maven and Docker are installed:

. Clone this project :

 $ git clone git://github.com/mgreau/asciidoctor-wildfly-docker.git

. Build the Docker image

  docker build -t asciidoctor/wildfly82 src/test/resources/wildfly/v8.2/

. Execute tests (Start a container / Execute tests / Stop and destroy the container)

  mvn clean test -Pwildfly82

  
[NOTE]
====
You can pass the docker server ip/port configuration with Maven properties :

  mvn clean test -Pwildfly82 -Ddocker.serverIp=192.168.59.103 -Ddocker.serverPort=27
====

== Errors

=== Error with asciidoctorj-epub3

The asciidoctorj-epub3 doesn't work for now, there is an error :

----
"(LoadError) load error: nokogiri/nokogiri -- java.lang.NoClassDefFoundError: com/sun/org/apache/xpath/internal/VariableStackHTML
----
