= asciidoctorj-wildfly

Arquillian Tests to verify that AsciidoctorJ works as a module in WildFly.

AsciidoctorJ is the Java library Wrapper for Asciidoctor.

It works on standalone mode but it can also be included into a Java app server so that Web applications can use it.

This project ensure that a AsciidoctorJ version and its dependencies work into severals WildFly version.+

For now, tests are :

* AsciidoctorJ 1.5.2 and WildFly 8.2.0

[IMPORTANT]
.Prerequisites
====
* JDK 7
* Apache Maven 3.1
* Docker configuration OK
====

== Let arquillian build the docker image and then execute tests :

* Build the asciidoctorj/wildfly docker image, run a container and execute arquillian test

  mvn clean test -Pwildfly82_dockerfile 
  
== Execute arquillian test in a "asciidoctorj/wildfly82" running container :

* Build the docker image

  cd src/main/resources/wildfly82
  docker build -t asciidoctorj/wildfly82 .

* Run a docker container with this image

* Execute tests

  mvn clean test -Pwildfly82
  
[NOTE]
====
You can pass your ip/port configuration with a Maven property :

  mvn clean test -Pwildfly82 -Darquillian.cube.serverUri=https://192.168.59.103:2376
====

== SSL Error

From : https://github.com/boot2docker/boot2docker/issues/573

cert.pem and key.pem files are used by the client side. With the docker command you specify the --cert and --key options. But browsers and some other application needs them in a combined form. That format called PKCS #12

  openssl pkcs12 -export \
  -inkey  key.pem \
  -in cert.pem \
  -name b2d-client-side \
  -out b2d-client-side.p12 \
  -password pass:tcuser
  
Now you need to import this p12 certificate. The import password is tcuser.
