= Asciidoctor uses Arquillian and Docker to easily ensure that AsciidoctorJ works into WildFly AS
Maxime Gréau
2015-03-01
:toc2: left
:awestruct-layout: post
:awestruct-tags: [asciidoctor, docker, wildfly, arquillian]
:link-asciidoctor-docker-hub: https://registry.hub.docker.com/repos/asciidoctor/
:link-asciidoctor: http://asciidoctor.org
:link-arquillian-cube-github: https://github.com/arquillian/arquillian-cube
:link-jboss-wildfly-docker: https://registry.hub.docker.com/u/jboss/wildfly/
:link-docker: http://docker.com

TIP: Language EN / Timereading 5 mn

It's been a while  since I wrote here but like many technicals blogger (I guess), I've a lot of blog posts on draft mode and I've a lot to write about 2014 which was 
an *amazing year* since thanks to the Asciidoctor project and Java EE 7 / WildFly technologies I speaked at DevNationn, San Francisco :)  but I'll blog about it soon.

So what about this post ?

You've just read the title and you said "Oh no ! Not another post about Docker!", and I want to answer "Well, it's 2015 Is it possible to blog without it's more a blog post about Asciidoctor and how Docker helps us to check that AsciidoctorJ can be execute into a Java EE application server like WildFly.
So it's not a post about Docker itself but how 

We will be talk about :
- Asciidoctor / AsciidoctorJ
- Docker
- Arquillian and Arquillian Cube
- WildFly AS


[NOTE]
.This post explains how we use Docker and Arquillian to check that AsciidoctorJ works into WildFly AS
====
* docker-asciidoctorj project
* Asciidoctor Docker
* WildFly AS
* Arquillian Cube extension 
====

pass::[more]

== Asciidoctor / AsciidoctorJ

Like you know now, Asciidoctor is a toolchain that give you the 
AsciidoctorJ is the JVM implementation 

== So what's the problem ?

The problem is that if you want to include AsciidoctorJ in your Java application, it's not easy. Indeed, AsciidoctorJ is base on JRUby and 
we have some classloader troubles with JRuby see bugs here =>

== How we solve it 

We tried 

=== How to test it easily 

=== Arquillian Cube extension

Arquillian Cube is an Aq
TODO => schema
TODO => exemple code

== AsciidoctorJ in another application server ? 

It seems that the JRuby classloader problem is solve with the use of JBoss Modules components but if you want to quickly 
If you're using another Java application server than WildFly AS like TomEE...feel free to fork the project and quickly tests if it works into
application server, here are the steps to follow :
 - Create a Dockerfile in a +dockerfiles+ subfolder, following the named convention +{appservername}{version}+
 - Update the arquillian XML file to add a docker container
 - Update the pom.xml to add Maven profiles related to the application server
 - Execute tests

We are waiting for PR :)

== Conclusion

The good news here is that the asciidoctor project now have an easy way to test if the future versions will be compatible with this architecture.
The other good news is that the 
Feel free to contact Guillaume Scheilorger or me if you have 

 
