= Asciidoctor uses Arquillian and Docker to easily ensure that AsciidoctorJ works into WildFly AS
Maxime Greau <greau.maxime@gmail.com>
v1.0, March 01, 2015: First English version
:awestruct-layout: post
:awestruct-tags: [asciidoctor, docker, wildfly, arquillian]
:toc2:
:toc-placement: preamble
:toc-title: Table of Contents
:source-highlighter: coderay
:linkattrs:
:sectanchors:
:sectlink:
:experimental:
:mdash: &#8212;
:language: asciidoc
:includedir: _includes
:icons: font
//Refs
:link-asciidoctor: http://asciidoctor.org
:link-asciidoctorj: http://asciidoctor.org
:link-devnation-talk: http://www.devnation.org/2014/#websocketAsciidoctor
:link-devnation-bof: http://www.devnation.org/2014/#bofWildfly8
:link-docker-asciidoctorj-github: http://github.com/mgreau/docker-asciidoctorj
:link-asciidoctor-docker-hub: https://registry.hub.docker.com/repos/asciidoctor/
:link-asciidoctor: http://asciidoctor.org
:link-arquillian-cube-github: https://github.com/arquillian/arquillian-cube
:link-jboss-wildfly-docker: https://registry.hub.docker.com/u/jboss/wildfly/
:link-docker: http://docker.com
:link-asciidoctorj-bug1: http://github.com/asciidoctor/asciidoctorj/issues
:link-asciidoctorj-bug2: http://github.com/asciidoctor/asciidoctorj/issues
:link-asciidoctorj-wildflyas-install: http://asciidoctor.org/docs/asciidoctorj/#running-asciidoctorj-on-wildfly-as
:link-twitter-dan-allen: http://twitter.com/mojavelinux

TIP: Language *_EN_* /  Timereading *_5 mn_*

[NOTE]
.This post explains how we execute Arquillian tests into a Docker container, so we'll talk about :
====
* {link-docker-asciidoctorj-github}[docker-asciidoctorj], the dedicated project on Asciidoctor organization
* {link-arquillian-cube-github}[arquillian-cube], the project from Arquillian community
* {link-jboss-wildfly-docker}[the WildFly docker image] from JBoss
====

It's been a while since I wrote here but like many technicals blogger (I guess), I've a lot of blog posts on draft mode and I've a lot to write about 2014 which was
an *AMAZING year* : indeed, thanks to the {link-asciidoctor}[*Asciidoctor project*] and +Java EE 7 / WildFly+ technologies, I gave *2 talks* at {link-devnation-talk}[+DevNation, San Francisco+] to speak about Open Source projects :)  +
But I'll blog about this +awesome experience+ soon.

*So what this post is about : Docker ? Asciidoctor ?*

You've just read the title and you said : +
- _"Oh no ! Not another post about Docker!"_, 
and I want to answer +
- _"Well, it's 2015, is it possible to write a blog post without mentionning Docker ?_" +

Serioulsy, it's more a blog post about the AsciidoctorJ project and how {link-docker}[Docker] helps us to easily check that AsciidoctorJ can be execute into a Java EE application server like WildFly. +
So it's not a post about Docker itself but more a use case where Docker is the key to the ease of tests...OK you're right, it's about Docker :)


pass::[more]

== Asciidoctor on the JVM with AsciidoctorJ

I guess that I don't need to introduce Asciidoctor now that it became so popular since it's was started by {link-twitter-dan-allen}[*Dan Allen*] at the end of 2012.
But
Like you know now, Asciidoctor is a toolchain that give you the

----
AsciidoctorJ is the official library for running Asciidoctor on the JVM.
Using AsciidoctorJ, you can convert AsciiDoc content or analyze the structure of a parsed AsciiDoc document from Java and other JVM languages
----

== So what's the problem ?

The problem is that if you want to include AsciidoctorJ in your Java application, it's not easy. Indeed, AsciidoctorJ is base on JRUby and
we have some classloader troubles with JRuby see bugs here =>

== How we solve it

We tried

=== How to test it easily

=== Arquillian Cube extension

Arquillian Cube is an Aq
TODO => schema
TODO => exemple code

== AsciidoctorJ in another application server ?

It seems that the JRuby classloader problem is solve with the use of JBoss Modules components but if you want to quickly
If you're using another Java application server than WildFly AS like TomEE...feel free to fork the project and quickly tests if it works into
application server, here are the steps to follow :
 - Create a Dockerfile in a +dockerfiles+ subfolder, following the named convention +{appservername}{version}+
 - Update the arquillian XML file to add a docker container
 - Update the pom.xml to add Maven profiles related to the application server
 - Execute tests and see the results

We are waiting for PR :)

== Conclusion

The good news here is that the asciidoctor project now have an easy way to test if the future versions will be compatible with this architecture.
The other good news is that the

Have fun with Asciidoctor, Arquillian and Docker :)
